import { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/header'
import { testMeta } from './projects/test.mdx'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>bramsinke</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <video
        autoPlay
        muted
        style={{
          width: '100vw',
          height: '50vh',
          objectFit: 'cover',
          position: 'absolute',
          top: 0,
          left: 0
        }}
      >
        <source src={testMeta.url} />
      </video>
      <Header />

      <main></main>

      <footer></footer>
    </div>
  )
}

export default Home
